package com.mycompany.javapos.gui;


import com.mycompany.javapos.dao.ProductDAO;
import com.mycompany.javapos.entity.EntityInvoiceDetail;
import com.mycompany.javapos.entity.EntityProduct;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



public class POS extends javax.swing.JFrame {
    //Product product = new Product(1, "Cafe", 10000);
    //List<Integer> selectedProductIds = new ArrayList<>();

    /**
     * Creates new form JavaPOS
     */
    public POS() {
        initComponents();
           // Thêm FocusListener cho jtxtDisplay
        jtxtDisplayDouble.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                // Khi jtxtDisplay nhận tiêu điểm, bạn có thể thực hiện một số hành động nếu cần
                System.out.println("jtxtDisplay has focus");
            }
        });

        // Thêm FocusListener cho jtxtDisplayPhoneNum
        jtxtDisplayDouble.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                // Khi jtxtDisplayPhoneNum nhận tiêu điểm, bạn có thể thực hiện một số hành động nếu cần
                System.out.println("jtxtDisplayPhoneNum has focus");
            }
        });

        // Đặt tiêu điểm vào jtxtDisplay khi khởi động (tùy chọn)
        jtxtDisplayDouble.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//=================================Funtion==================================================================================
    public void itemcost()
    {
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        double cTax = (cTotal1 * 3.9)/100;
        //String iTaxTotal = String.format("$ %.2f", cTax);
        jtxtTax.setText(String.format("%s VND",numberFormat.format(cTax)));
        
        //String iSubTotal = String.format("$ %.2f", cTotal1);
        jtxtSubTotal.setText(String.format("%s VND",numberFormat.format(cTotal1)));
        
        //String iTotal = String.format("$ %.2f", cTotal1 + cTax);
        jtxtTotal.setText(String.format("%s VND",numberFormat.format(cTotal1 + cTax)));
        
        //String BarCode = String.format("Total is %.2f", cTotal1);
        //jtxtBarCode.setText(iSubTotal);
        
    }
    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplayDouble.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9)/100;
        double cChange = (cash - (sum + cTax));
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
        //String ChangeGiven = String.format("$ %.2f", cChange);
        jtxtChange.setText(String.format("%s VND",numberFormat.format(cChange)));
    }

    private void updateDisplayWithNumber(String number) {
        String currentNumber = jtxtDisplay.getText();

        // Xóa dấu phẩy khỏi chuỗi hiện tại
        currentNumber = currentNumber.replaceAll(",", "");

        // Thêm số mới vào chuỗi hiện tại
        currentNumber += number;

        // Định dạng chuỗi hiện tại để thêm dấu phẩy
        try {
            String formattedValue = formatNumberWithCommas(currentNumber);
            jtxtDisplay.setText(formattedValue);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Hàm định dạng chuỗi với dấu phẩy
    private String formatNumberWithCommas(String number) {
        // Tách phần nguyên và phần thập phân
        String[] parts = number.split("\\.");
        // Định dạng phần nguyên với dấu phẩy
        String integerPart = parts[0].replaceAll("(\\d)(?=(\\d{3})+$)", "$1,");
        if (parts.length > 1) {
            // Nếu có phần thập phân, nối lại với dấu chấm
            return integerPart + "." + parts[1];
        } else {
            // Nếu không có phần thập phân, trả về phần nguyên
            return integerPart;
        }
    }

    private void handleNumberInput(String number) {
        String currentText = jtxtDisplayDouble.getText();
        
        // Kiểm tra nếu ô nhập trống
        if (currentText.isEmpty()) {
            jtxtDisplayDouble.setText(number);
        } else {
            // Nối số mới vào chuỗi hiện tại
            currentText += number;
            jtxtDisplayDouble.setText(currentText);
        }
    }
    
    private void PrintToPdf()
    {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                int xMargin = 50; // Lề trái
                int y = 50;       // Vị trí bắt đầu theo trục dọc (y-axis)

                // Tiêu đề "HÓA ĐƠN THANH TOÁN"
                String title = "HÓA ĐƠN THANH TOÁN";
                Font titleFont = new Font("Serif", Font.BOLD, 20);
                g.setFont(titleFont);
                g.drawString(title, xMargin, y);
                y += 40; // Xuống dòng sau tiêu đề

                // In JTable
                g2d.translate(xMargin, y); // Đặt JTable tại vị trí lề trái
                jTable1.printAll(g);
                g2d.translate(-xMargin, -y); // Reset lại vị trí vẽ
                y += jTable1.getHeight() + 20; // Xuống dòng dưới JTable

                // Lấy thông tin từ JTextField
                String subTotal = "Subtotal: " + jtxtSubTotal.getText();
                String tax = "Tax: " + jtxtTax.getText();
                String total = "Total: " + jtxtTotal.getText();
                String cash = "Cash: " + jtxtDisplay.getText();
                String change = "Change: " + jtxtChange.getText();

                // Định dạng font cho thông tin
                Font textFont = new Font("Serif", Font.PLAIN, 14);
                g.setFont(textFont);

                // In từng thông tin, căn lề trái
                String[] infoLines = {subTotal, tax, total, cash, change};
                for (String line : infoLines) {
                    g.drawString(line, xMargin, y);
                    y += 20; // Xuống dòng
                }

                return PAGE_EXISTS;
            }
        });

        // Hiển thị hộp thoại in
        boolean doPrint = job.printDialog();
        if (doPrint) {
            try {
                job.print();
            } catch (PrinterException e) {
                System.err.println("Printing failed: " + e.getMessage());
            }
        }
    }
//=================================Funtion==================================================================================

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnMenu3 = new javax.swing.JButton();
        jbtnMenu1 = new javax.swing.JButton();
        jbtnMenu2 = new javax.swing.JButton();
        jbtnMenu4 = new javax.swing.JButton();
        jbtnMenu5 = new javax.swing.JButton();
        jbtnMenu6 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jbtnMenu7 = new javax.swing.JButton();
        jbtnMenu8 = new javax.swing.JButton();
        jbtnMenu9 = new javax.swing.JButton();
        jbtnMenu10 = new javax.swing.JButton();
        jbtnMenu11 = new javax.swing.JButton();
        jbtnMenu12 = new javax.swing.JButton();
        jbtnMenu13 = new javax.swing.JButton();
        jbtnMenu14 = new javax.swing.JButton();
        jbtnMenu15 = new javax.swing.JButton();
        jbtnMenu16 = new javax.swing.JButton();
        jbtnMenu17 = new javax.swing.JButton();
        jbtnMenu18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtDisplay = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnInvoice = new javax.swing.JButton();
        jtxtDisplayDouble = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnNum9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 90));

        jbtnNum7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 80, 90));

        jbtnNum8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 90));

        jbtnNum4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 90));

        jbtnNum5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, 90));

        jbtnNum6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, 90));

        jbtnNum1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 90));

        jbtnNum2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 90));

        jbtnNum3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 90));

        jbtnNum0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNum0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNum0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 90));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 90));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 80, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 490));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnMenu3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\3.png")); // NOI18N
        jbtnMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 130));

        jbtnMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\1.png")); // NOI18N
        jbtnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 130));

        jbtnMenu2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\2.GIF")); // NOI18N
        jbtnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 130));

        jbtnMenu4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\4.png")); // NOI18N
        jbtnMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 130));

        jbtnMenu5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\5.png")); // NOI18N
        jbtnMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 130));

        jbtnMenu6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\6.png")); // NOI18N
        jbtnMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 130));

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton19.setText("9");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton20.setText("9");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 110));

        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton21.setText("9");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 110));

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton34.setText("9");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton35.setText("9");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 110));

        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton36.setText("9");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 110));

        jButton37.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton37.setText("9");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 110));

        jButton38.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton38.setText("9");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 110));

        jButton39.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton39.setText("9");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 110));

        jbtnMenu7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\7.png")); // NOI18N
        jbtnMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 130));

        jbtnMenu8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\8.png")); // NOI18N
        jbtnMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, 130));

        jbtnMenu9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\9.png")); // NOI18N
        jbtnMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, 130));

        jbtnMenu10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\10.png")); // NOI18N
        jbtnMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu10ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, 130));

        jbtnMenu11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\11.png")); // NOI18N
        jbtnMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu11ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 130));

        jbtnMenu12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\12.png")); // NOI18N
        jbtnMenu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu12ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 120, 130));

        jbtnMenu13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\13.png")); // NOI18N
        jbtnMenu13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu13ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 130));

        jbtnMenu14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\14.png")); // NOI18N
        jbtnMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu14ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 130));

        jbtnMenu15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\15.png")); // NOI18N
        jbtnMenu15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu15ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 120, 130));

        jbtnMenu16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\16.png")); // NOI18N
        jbtnMenu16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu16ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 120, 130));

        jbtnMenu17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\17.png")); // NOI18N
        jbtnMenu17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu17ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 120, 130));

        jbtnMenu18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMenu18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\18.png")); // NOI18N
        jbtnMenu18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenu18ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMenu18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 120, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 780, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 300, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tax");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("SubTotal");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel11.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel11.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, -1));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel11.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, -1));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 160));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Cash");
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Change");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Payment");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel12.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa", "Master Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel12.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel12.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 350, 160));

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 50));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 50));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Lock Screen");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 50));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel13.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 50));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 610, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1380, 200));

        jbtnInvoice.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtnInvoice.setText("Invoice");
        jbtnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 80, 30));

        jtxtDisplayDouble.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtDisplayDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayDoubleActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDisplayDouble, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 448, 150, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huy\\school\\HDT-java\\pos\\javaPOS\\src\\main\\java\\img\\lockscreen.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, 1390, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu3ActionPerformed
        int id = 3;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu3ActionPerformed

    private void jbtnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu1ActionPerformed
        int id = 1;
        //add id in to list bills
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); // Cập nhật chi phí
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }

    }//GEN-LAST:event_jbtnMenu1ActionPerformed

    private void jbtnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu2ActionPerformed
        int id = 2;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu2ActionPerformed

    private void jbtnMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu4ActionPerformed
        int id = 4;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu4ActionPerformed

    private void jbtnMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu5ActionPerformed
        int id = 5;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu5ActionPerformed

    private void jbtnMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu6ActionPerformed
        int id = 6;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu6ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // clear
        jtxtDisplayDouble.setText("");
        jtxtChange.setText("");
        jtxtDisplay.setText("");
        
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jtxtDisplayDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayDoubleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayDoubleActionPerformed

    private void jbtnMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu7ActionPerformed
        int id = 7;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu7ActionPerformed

    private void jbtnMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu8ActionPerformed
        //double priceOfItem = 3.40;
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //model.addRow(new Object[]{"Rainbow Cake", "1", priceOfItem});
        //itemcost();
        int id = 8;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu8ActionPerformed

    private void jbtnMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu9ActionPerformed
        int id = 9;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu9ActionPerformed

    private void jbtnMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu10ActionPerformed
        int id = 10;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu10ActionPerformed

    private void jbtnMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu11ActionPerformed
        int id = 11;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu11ActionPerformed

    private void jbtnMenu12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu12ActionPerformed
        int id = 12;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu12ActionPerformed

    private void jbtnMenu13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu13ActionPerformed
        int id = 13;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu13ActionPerformed

    private void jbtnMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu14ActionPerformed
        int id = 14;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu14ActionPerformed

    private void jbtnMenu15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu15ActionPerformed
        int id = 15;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu15ActionPerformed

    private void jbtnMenu16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu16ActionPerformed
        int id = 16;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu16ActionPerformed

    private void jbtnMenu17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu17ActionPerformed
        int id = 17;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu17ActionPerformed

    private void jbtnMenu18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenu18ActionPerformed
        int id = 18;
        ProductDAO productDAO = new ProductDAO();
        EntityProduct product = productDAO.getProductById(id);
        if (product != null) { 
            String nameOfItem = product.getNameProduct(); 
            double priceOfItem = product.getPrice(); 
        
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{nameOfItem, "1", priceOfItem}); 
            itemcost(); 
        } else {
            System.out.println("Sản phẩm không tồn tại.");
        }
    }//GEN-LAST:event_jbtnMenu18ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        //0
        handleNumberInput("0");
        updateDisplayWithNumber("0");
//        String Enternumber = jtxtDisplay.getText();
//        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
//
//        if (Enternumber.isEmpty()) {
//            // Nếu trường trống, đặt giá trị là "0"
//            jtxtDisplay.setText(jbtnNum0.getText());
//        } else {
//            // Nối số mới vào chuỗi hiện tại
//            Enternumber += jbtnNum0.getText();
//
//            // Chuyển đổi chuỗi thành số
//            try {
//                double value = Double.parseDouble(Enternumber);
//                // Định dạng số với dấu phẩy
//                String formattedValue = numberFormat.format(value);
//                jtxtDisplay.setText(formattedValue);
//            } catch (NumberFormatException e) {
//                // Xử lý nếu không thể chuyển đổi thành số
//                JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            }
//        }
        
        
        //========================
//        String Enternumber = jtxtDisplay.getText();
//        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum0.getText());
//            //jtxtDisplay.setText(String.format("%s VND", numberFormat.format(jbtnNum0.getText())));
//            //String.format("Tổng doanh thu: %s VND", numberFormat.format(totalRevenue))
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum0.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
        //=======================
        //addNumberToFocusedField("0");
        //handleNumberInput("0");
//        System.out.println("Nút 0 đã được nhấn.");
//        if (jtxtDisplay.isFocusOwner()) {
//            System.out.println("jtxtDisplay đang được chọn.");
//            String Enternumber = jtxtDisplay.getText();
//            System.out.println("Giá trị hiện tại của jtxtDisplay: " + Enternumber);
//            if (Enternumber == "")
//            {
//                jtxtDisplay.setText(jbtnNum0.getText());
//            }
//            else{
//                Enternumber = jtxtDisplay.getText() + jbtnNum1.getText();
//                jtxtDisplay.setText(Enternumber);
//            }
//            
//        } else if (jtxtDisplayPhoneNum.isFocusOwner()) {
//            String Enternumber = jtxtDisplayPhoneNum.getText();
//            if (Enternumber == "")
//            {
//                jtxtDisplayPhoneNum.setText(jbtnNum0.getText());
//            }
//            else
//            {
//                Enternumber = jtxtDisplayPhoneNum.getText() + jbtnNum1.getText();
//                jtxtDisplayPhoneNum.setText(Enternumber);
//            }
//        }
//            
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        handleNumberInput("7");
        updateDisplayWithNumber("7");
//        String Enternumber = jtxtDisplay.getText();
//        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
//
//        if (Enternumber.isEmpty()) {
//            // Nếu trường trống, đặt giá trị là "0"
//            jtxtDisplay.setText(jbtnNum0.getText());
//        } else {
//            // Nối số mới vào chuỗi hiện tại
//            Enternumber += jbtnNum0.getText();
//
//            // Chuyển đổi chuỗi thành số
//            try {
//                double value = Double.parseDouble(Enternumber);
//                // Định dạng số với dấu phẩy
//                String formattedValue = numberFormat.format(value);
//                jtxtDisplay.setText(formattedValue);
//            } catch (NumberFormatException e) {
//                // Xử lý nếu không thể chuyển đổi thành số
//                JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            }
//        }
// 7
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum7.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum7.getText();
//            jtxtDisplay.setText(Enternumber);
//        }updateDisplayWithNumber("8");
        
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        updateDisplayWithNumber("8");
        handleNumberInput("8");
        // 8:
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum8.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum8.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        updateDisplayWithNumber("9");
        handleNumberInput("0");
//        // 9
//        String Enternumber = jtxtDisplay.getText();
//
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum9.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum9.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        // 4
        handleNumberInput("4");
        updateDisplayWithNumber("4");
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum4.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum4.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        // 5:
        handleNumberInput("5");
        updateDisplayWithNumber("5");
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum5.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum5.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
        
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        // 6
        handleNumberInput("6");
        updateDisplayWithNumber("6");
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum6.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum6.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        // 1
        handleNumberInput("1");
        updateDisplayWithNumber("1");

    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        // 2
        handleNumberInput("2");
        updateDisplayWithNumber("2");
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        // 3
        handleNumberInput("3");
        updateDisplayWithNumber("3");
//        String Enternumber = jtxtDisplay.getText();
//        
//        if (Enternumber == "")
//        {
//            jtxtDisplay.setText(jbtnNum3.getText());
//        }
//        else{
//            Enternumber = jtxtDisplay.getText() + jbtnNum3.getText();
//            jtxtDisplay.setText(Enternumber);
//        }
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        // dot
        if(! jtxtDisplayDouble.getText().contains("."))
        {
            jtxtDisplayDouble.setText(jtxtDisplayDouble.getText() + jbtnDot.getText());
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        double cash = Double.parseDouble(jtxtDisplayDouble.getText());
        if (jcboPayment.getSelectedItem().equals("Cash")) {
            Change(); // Tính tiền thối

            // Tính toán tổng tiền và thuế
            double sum = 0.0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString().replace("$", "").trim());
            }

            double tax = sum * 0.039;
            double grandTotal = sum + tax;

            if (cash < grandTotal){
                JOptionPane.showMessageDialog(this, "Số tiền mặt không đủ! Vui lòng nhập lại.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                jtxtDisplayDouble.setText("");
                return;
            }

            // Tạo danh sách chi tiết hóa đơn
            List<EntityInvoiceDetail> invoiceDetails = new ArrayList<>();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String productName = (String) jTable1.getValueAt(i, 0);
                int quantity = Integer.parseInt((String) jTable1.getValueAt(i, 1));
                double price = Double.parseDouble(jTable1.getValueAt(i, 2).toString().replace("$", "").trim());
                invoiceDetails.add(new EntityInvoiceDetail(productName, quantity, price));
            }

            // Lưu hóa đơn vào cơ sở dữ liệu
            ProductDAO productDAO = new ProductDAO();
            productDAO.saveInvoice(sum, tax, grandTotal, invoiceDetails);

            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Hóa đơn đã được lưu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Reset bảng và các trường nhập liệu
            //jbtnResetActionPerformed(evt);
        } else {
            jtxtChange.setText("");
            jtxtDisplayDouble.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplayDouble.setText("");
        jtxtDisplayDouble.setText("");
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        PrintToPdf();
        JOptionPane.showMessageDialog(this, "Hóa đơn đã được in thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if (RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        itemcost();
        if (jcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplayDouble.setText("");
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to Lock Screen!", "Point of Sale", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            LockScreen lockscreen = new LockScreen();
            lockscreen.setVisible(true);
            this.dispose();
        }
        
//        frame = new JFrame("Exit");
//        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "Point of Sale", 
//                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
//        {
//            System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInvoiceActionPerformed
        // go to Invoice.java
        Invoice invoiceScreen = new Invoice();
        invoiceScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnInvoiceActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnInvoice;
    private javax.swing.JButton jbtnMenu1;
    private javax.swing.JButton jbtnMenu10;
    private javax.swing.JButton jbtnMenu11;
    private javax.swing.JButton jbtnMenu12;
    private javax.swing.JButton jbtnMenu13;
    private javax.swing.JButton jbtnMenu14;
    private javax.swing.JButton jbtnMenu15;
    private javax.swing.JButton jbtnMenu16;
    private javax.swing.JButton jbtnMenu17;
    private javax.swing.JButton jbtnMenu18;
    private javax.swing.JButton jbtnMenu2;
    private javax.swing.JButton jbtnMenu3;
    private javax.swing.JButton jbtnMenu4;
    private javax.swing.JButton jbtnMenu5;
    private javax.swing.JButton jbtnMenu6;
    private javax.swing.JButton jbtnMenu7;
    private javax.swing.JButton jbtnMenu8;
    private javax.swing.JButton jbtnMenu9;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtDisplayDouble;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
